# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 19:52
from __future__ import unicode_literals

from django.db import migrations


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Magic = apps.get_model("fakepolls", "Magic")
    m0 = Magic(name_text='lightning bolt', type_text='instant', color_text='red', cmc_num=1, rarity_text='common', price_num=2.99, artist_text='christopher rush', cardset_text='alpha')
    m1 = Magic(name_text='island', type_text='land', color_text='colorless', cmc_num=0, rarity_text='common', price_num=0.01, artist_text='mark poole', cardset_text='alpha')
    m2 = Magic(name_text='jace the mindsculptor', type_text='planeswalker', color_text='blue', cmc_num=4, rarity_text='mythic', price_num=75.00, artist_text='jason chan', cardset_text='worldwake')
    m3 = Magic(name_text='tarmogoyf', type_text='creature', color_text='green', cmc_num=2, rarity_text='rare', price_num=130.00, artist_text='justin murray', cardset_text='future sight')
    m4 = Magic(name_text='damnation', type_text='sorcery', color_text='black', cmc_num=4, rarity_text='rare', price_num=63.00, artist_text='kev walker', cardset_text='planar chaos')
    m5 = Magic(name_text='blood moon', type_text='enchantment', color_text='red', cmc_num=3, rarity_text='rare', price_num=42.00, artist_text='tom wanerstrand', cardset_text='the dark')
    m6 = Magic(name_text='vendilion clique', type_text='creature', color_text='blue', cmc_num=3, rarity_text='rare', price_num=30.00, artist_text='michael sutfin', cardset_text='morningtide')
    m7 = Magic(name_text='path to exile', type_text='instant', color_text='white', cmc_num=1, rarity_text='uncommon', price_num=11.00, artist_text='todd lockwood', cardset_text='conflux')
    m8 = Magic(name_text='platinum emperion', type_text='creature', color_text='colorless', cmc_num=8, rarity_text='mythic', price_num=20.66, artist_text='chris rahn', cardset_text='scars of mirrodin')
    m9 = Magic(name_text='counterbalance', type_text='enchantment', color_text='blue', cmc_num=2, rarity_text='uncommon', price_num=18.79, artist_text='john zeleznik', cardset_text='coldsnap')
    m10 = Magic(name_text='ensnaring bridge', type_text='artifact', color_text='colorless', cmc_num=3, rarity_text='rare', price_num=37.35, artist_text='pete venters', cardset_text='stronghold')
    m11 = Magic(name_text='demonic tutor', type_text='sorcery', color_text='black', cmc_num=2, rarity_text='uncommon', price_num=335.99, artist_text='douglas schuler', cardset_text='alpha')
    m12 = Magic(name_text='pact of the titan', type_text='instant', color_text='red', cmc_num=0, rarity_text='rare', price_num=5.90, artist_text='raymond swanland', cardset_text='future sight')
    m13 = Magic(name_text='primeval titan', type_text='creature', color_text='green', cmc_num=6, rarity_text='mythic', price_num=9.25, artist_text='aleksi briclot', cardset_text='m11')
    m14 = Magic(name_text='city of brass', type_text='land', color_text='colorless', cmc_num=0, rarity_text='uncommon', price_num=124.29, artist_text='mark tedin', cardset_text='arabian nights')
    m15 = Magic(name_text='forked bolt', type_text='sorcery', color_text='red', cmc_num=1, rarity_text='uncommon', price_num=0.72, artist_text='tomasz jedruszek', cardset_text='rise of the eldrazi')
    m16 = Magic(name_text='grim monolith', type_text='artifact', color_text='colorless', cmc_num=2, rarity_text='rare', price_num=48.52, artist_text='chippy', cardset_text='urzas legacy')
    m0.save()
    m1.save()
    m2.save()
    m3.save()
    m4.save()
    m5.save()
    m6.save()
    m7.save()
    m8.save()
    m9.save()
    m10.save()
    m11.save()
    m12.save()
    m13.save()
    m14.save()
    m15.save()
    m16.save()
    # for magic in Magic.objects.all():
    #     magic.name = "{}".format(magic.name_text)
    #     magic.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('fakepolls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
